export const LINKS = {
  homeLink: '/',
  loginLink: '/login',
  dashboardLink: '/dashboard',
  documentsLink: '/documents',
  documentsUploadLink: '/documents/upload',
  documentsCategoryLink: '/documents/categories',
  coursesLink: '/courses',
  coursesUploadLink: '/courses/upload',
  coursesCategoryLink: '/courses/categories',
  newsLink: '/news',
  newsUploadLink: '/news/upload',
  newsCategoryLink: '/news/categories',
  testsLink: '/tests',
  usersLink: '/users',
};